# Generated by Django 6.0 on 2026-01-06 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_hours', models.PositiveIntegerField()),
                ('medium_hours', models.PositiveIntegerField()),
                ('high_hours', models.PositiveIntegerField()),
                ('urgent_hours', models.PositiveIntegerField()),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policy', to='accounts.plan')),
            ],
        ),
    ]
