# Generated by Django 6.0 on 2026-01-07 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'create'), ('UPDATE', 'update'), ('DELETE', 'delete')], max_length=10)),
                ('object_type', models.CharField(choices=[('TICKET', 'ticket'), ('REPLY', 'reply'), ('PLANREQUEST', 'planrequest'), ('ETC', 'etc')], max_length=15)),
                ('object_id', models.PositiveIntegerField()),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
